name: Release
on:
  push:
    branches:
    - main
    tags:
    - "v*"

jobs:
  release:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
        submodules: true
    - uses: coursier/cache-action@v8.1
      with:
        extraFiles: "[\".github/scripts/*\", \".github/workflows/ci.yml\", \"*.sh\"]"
        extraKey: "release"
    - name: Release
      run: ./mill -i mill.scalalib.SonatypeCentralPublishModule/
      env:
        MILL_PGP_SECRET_BASE64: ${{ secrets.PUBLISH_SECRET_KEY }}
        MILL_PGP_PASSPHRASE: ${{ secrets.PUBLISH_SECRET_KEY_PASSWORD }}
        MILL_SONATYPE_USERNAME: ${{ secrets.PUBLISH_USER }}
        MILL_SONATYPE_PASSWORD: ${{ secrets.PUBLISH_PASSWORD }}
